# Generated by Django 5.1 on 2024-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFigure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('given_names', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(blank=True, max_length=4, null=True)),
                ('death_year', models.CharField(blank=True, max_length=4, null=True)),
                ('short_description', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Historical figure information management',
                'verbose_name_plural': 'Historical figure information management',
                'db_table': 'historical_figure',
            },
        ),
    ]
