# Generated by Django 5.1 on 2024-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfigure',
            name='birth_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='death_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
