# Generated by Django 5.1.2 on 2024-10-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_alter_historicalfigure_birth_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalfigure",
            name="biography_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
